global_frame: map
rolling_window: true # lay robot lam tam

plugins:
  
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"} 
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}